site_name: Kelp
theme:
  name: material
  icon:
    logo: material/leaf-circle
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: green
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: green
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  features:
    - content.code.annotate
    - content.code.copy
    - content.footnote.tooltips
    - content.tabs.link
    - navigation.tabs
repo_name: BenSchr/kelp
repo_url: https://github.com/BenSchr/kelp
plugins:
  - search
  - offline
  - autorefs
  - mkdocstrings:
      handlers:
        python:
          paths: [src]
          options:
            extensions:
              - dataclasses
              - griffe_pydantic:
                  schema: true
            show_if_no_docstring: true
            filters:
              - "!^_"
            show_symbol_type_heading: true
            show_symbol_type_toc: true
            inherited_members: true
            show_root_heading: true
            members_order: source
            separate_signature: true
            merge_init_into_class: true
            docstring_section_style: spacy
            signature_crossrefs: true

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
