"""Generic model metadata API for use in any Spark job."""

from kelp.config import init
from kelp.tables.api import (
    columns,
    ddl,
    func,
    get_model,
    ref,
    schema,
    schema_lite,
    source,
    source_options,
)
from kelp.tables.materialization import (
    REGISTRY,
    AppendConfig,
    ColumnSelector,
    FullRefreshStrategy,
    MaterializationConfig,
    MaterializationOptions,
    MaterializedContext,
    MergeConfig,
    ModelRegistry,
    ModelSpec,
    OverwriteConfig,
    Runner,
    Scd2Columns,
    Scd2Config,
    SqlConditions,
    materialize,
    materialized,
)

__all__ = [
    "REGISTRY",
    "AppendConfig",
    "ColumnSelector",
    "FullRefreshStrategy",
    "MaterializationConfig",
    "MaterializationOptions",
    "MaterializedContext",
    "MergeConfig",
    "ModelRegistry",
    "ModelSpec",
    "OverwriteConfig",
    "Runner",
    "Scd2Columns",
    "Scd2Config",
    "SqlConditions",
    "columns",
    "ddl",
    "func",
    "get_model",
    "init",
    "materialize",
    "materialized",
    "ref",
    "schema",
    "schema_lite",
    "source",
    "source_options",
]
